a1 = (input('digite algo : '))
ty = type(a1)
print(f'o tipo primitivo desse valor e {ty}')
print(f'so tem espaços? {a1.isspace()}')
print(f'e numero? {a1.isnumeric()}')
print(f'e alfabetico? {a1.isalpha()}')
print(f'É alfanumérico? {a1.isalnum()}')
print(f'Está em maiúsculas? {a1.isupper()}')
print(f'Está em minúsculas? {a1.islower()}')
print(f'Está capitalizada? {a1.istitle()}')
