colocados = ('palmeiras', 'flamengo', 'atheletico-pr', 'fluminense', 'bahia', 'cruzeiro', 'curitiba', 'atheletico-mg', 'bragantina', 'corinthians', 'sao paulo', 'botafogo', 'vitoria', 'santos', 'gremio', 'mirassol', 'vasco', 'internacional', 'remo', 'chapecoense')
print('-=-' * 20)
print(f'lista do brasileirao: {colocados}')
print('-=-' * 20)
print(f'os 5 primeiros sao {colocados[0:5]}')
print('-=-' * 20)
print(f'os 4 ultimos sao {colocados[-4:]}')
print('-=-' * 20)
print(f'times em ordem alfabetica: {sorted(colocados)}')
print('-=-' * 20)
print(f'o chapecoense esta na {colocados.index('chapecoense') + 1}a posiçao')
